name: 'string changes monitor.'
description: 'Monitors for changes to specific strings.'
author: 'yokobot - Takao Yokoyama'

inputs:
  file:
    description: 'File to monitor.'
    required: true
  line:
    description: 'Number of lines to monitor.'
    required: true
  string:
    description: 'Expected string.'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'shield'
  color: 'green'
